substitutions:
  upd_frq: 60s
  ir_dump: "pioneer"
  remote: "VSX-520"
  led_dur: 250ms

button:
  - platform: template
    name: "Mute"
    on_press:
      - binary_sensor.template.publish:
          id: ir_transmitting
          state: ON
      - script.execute: update_ir_led
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          repeat:
            times: 2
      - binary_sensor.template.publish:
          id: ir_transmitting
          state: OFF
      - script.execute: update_ir_led

binary_sensor:
  - platform: template
    id: ir_receiving
    internal: true
  - platform: template
    id: ir_transmitting
    internal: true
# HERE
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Physical Button
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          rc_code_2: 0xA512

remote_receiver:
  id: IR_Receiver
  pin:
    number: GPIO13
    inverted: true
  dump: ${ir_dump}
  tolerance: 25%
  on_raw:
    then:
      - if:
          condition:
            binary_sensor.is_off: ir_transmitting
          then:
            - binary_sensor.template.publish:
                id: ir_receiving
                state: ON
            - script.execute: update_ir_led
            - delay: ${led_dur}
            - binary_sensor.template.publish:
                id: ir_receiving
                state: OFF
            - script.execute: update_ir_led

remote_transmitter:
  id: IR_Transmitter
  pin: GPIO12
  carrier_duty_percent: 50%

infrared:
  - platform: ir_rf_proxy
    name: IR Receiver
    receiver_frequency: 38kHz
    remote_receiver_id: IR_Receiver
  - platform: ir_rf_proxy
    name: IR Transmitter
    remote_transmitter_id: IR_Transmitter

sensor:
  - platform: dht
    model: "DHT11"
    pin: GPIO21
    id: sensor_dht11
    temperature:
      id: "temperature"
      name: "DHT11 Temperature"
    humidity:
      id: "humidity"
      name: "DHT11 Humidity"
      # on_value_range:
      #   - above: 65.0
      #     then:
      #       - switch.turn_on: dehumidifier1
      #   - below: 50.0
      #     then:
      #       - switch.turn_off: dehumidifier1
    update_interval: ${upd_frq}
    
output:
  - platform: ledc
    id: rgb_gpio_16
    pin: GPIO16
  - platform: ledc
    id: rgb_gpio_18
    pin: GPIO18
  - platform: ledc
    id: rgb_gpio_17
    pin: GPIO17

light:
  - platform: rgb
    name: RGB Light
    id: light_rgb_1
    blue: rgb_gpio_16
    green: rgb_gpio_18
    red: rgb_gpio_17

script:
  - id: update_ir_led
    mode: restart
    then:
      - if:
          condition:
            and:
              - binary_sensor.is_on: ir_receiving
              - binary_sensor.is_on: ir_transmitting
          then:
            - light.turn_on:
                id: light_rgb_1
                red: 0%
                green: 0%
                blue: 100%
                brightness: 100%
                transition_length: 0s
            - delay: ${led_dur}
            - light.turn_off:
                id: light_rgb_1
                transition_length: 0s
      - if:
          condition:
            and:
              - binary_sensor.is_on: ir_receiving
              - binary_sensor.is_off: ir_transmitting
          then:
            - light.turn_on:
                id: light_rgb_1
                red: 100%
                green: 0%
                blue: 0%
                brightness: 100%
                transition_length: 0s
            - delay: ${led_dur}
            - light.turn_off:
                id: light_rgb_1
                transition_length: 0s
      - if:
          condition:
            and:
              - binary_sensor.is_off: ir_receiving
              - binary_sensor.is_on: ir_transmitting
          then:
            - light.turn_on:
                id: light_rgb_1
                red: 0%
                green: 100%
                blue: 0%
                brightness: 100%
                transition_length: 0s
            - delay: ${led_dur}
            - light.turn_off:
                id: light_rgb_1
                transition_length: 0s
      - if:
          condition:
            and:
              - binary_sensor.is_off: ir_receiving
              - binary_sensor.is_off: ir_transmitting
          then:
            - light.turn_off:
                id: light_rgb_1
                transition_length: 0s




